service:
  name: serverless-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  profile: experiment_sls
  runtime: nodejs8.10

functions:
  hello:
    handler: src/hello.hello
    events:
      - http:
          method: GET
          path: hello
  get-quote:
    handler: src/quotes.michaelscott
    events:
      - http:
          method: GET
          path: quote
          cors: true
  send-quote:
    handler: src/quotes.michaelscott
    events:
      - http:
          method: POST
          path: quote
          cors: true
      - schedule: cron(0 14 ? * MON-FRI *)
#      - schedule: rate(60 minutes)
