service:
  name: serverless-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  profile: experiment_sls
  runtime: nodejs8.10

functions:
  hello:
    handler: src/hello.hello
    events:
      - http:
          method: GET
          path: hello
  inspirational-quote:
    handler: src/quotes.michaelscott
    events:
      - http:
          method: GET
          path: send-quote
      - schedule: rate(10 minutes)
    memorySize: 128
